apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    type: web-app
spec:
  containers:
    - name: web-server-apache
      image: httpd
      ports:
        - containerPort: 80
    - name: web-server-tomcaat
      image: tomcat
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  selector: #seleciona qual pod esse serviço vai se conectar
    type: web-app
  ports:
    - name: http
      port: 80 #porta de acesso ao serviço
      targetPort: 80 # opcional, quando não definido, o k8s atribui o valor de port automaticamente para ele