apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    type: web-app
spec:
  containers:
    - name: web-server-apache
      image: httpd
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    type: web-app
  ports:
    - name: http
      port: 80 #porta de acesso ao serviço
      targetPort: 80 # opcional, quando não definido, o k8s atribui o valor de port automaticamente para ele
      nodePort: 30009 # opcional, mas se não for definido, o k8s define um valor randômico