apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: default

data:
  #Connection database config
  database: mysql
  database_uri: mysql://localhost:3306
  #user interface
  font.title: Arial Bold
  backround-color: red
  theme.1: clean
  theme.2: dark
#  1theme.2: dark # variavel com nome invalido, não pode começar com numero
---
apiVersion: v1
kind: Pod

metadata:
  name: pod-configmap-env

spec:
  containers:
    - name: my-container
      image: nginx
      envFrom:
      - configMapRef:
          name: my-configmap # escolhe o configmap para aplicar no container