apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap

data:
  #Connection database config
  database: mysql
  database_uri: mysql://localhost:3306
---
apiVersion: v1
kind: Pod

metadata:
  name: pod-configmap-env

spec:
  containers:
    - name: my-container
      image: nginx
      envFrom:
      - configMapRef:
          name: my-configmap # escolhe o configmap para aplicar no container
      command:
      - "bin/sh"
      - "-c"
      - "echo My Database = $database - $database_uri"
  restartPolicy: Never