apiVersion: apps/v1
kind: DaemonSet #tipo de recurso
metadata:
  name: my-daemonset
  labels:
    app: frontend

spec: # Especificações referente ao pod que será criado
  updateStrategy: #Definindo uma estratégia de atualização, por default é RollingUpdate
    type: OnDelete
#    rollingUpdate:
#      maxUnavailable: 2 # Aqui realmente está modificando o default, de 1 para 2
  template:
    metadata: ##metadata referente ao pod
      name: my-pod-webserver
      labels:
        apps: my-app
        tier: frontend
    spec: # Especificações referente ao container do pod que será criado
      containers:
      - name: my-container-nginx
        image: tomcat

  selector: #seleciona o pod para criar replicas através da label do pod
    matchLabels:
     apps: my-app
     #daemonset dispensa especificar a quantidade de replica, pois ele vai replicar o pod em todos os nodes disponíveis
     #automaticamente