apiVersion: apps/v1
kind: DaemonSet #tipo de recurso
metadata:
  name: my-daemonset
  labels:
    app: frontend

spec: # Especificações referente ao pod que será criado
  template:
    metadata: ##metadata referente ao pod
      name: my-pod-webserver
      labels:
        apps: my-app
        tier: frontend
    spec: # Especificações referente ao container do pod que será criado
      containers:
      - name: my-container-nginx
        image: nginx
      nodeSelector: #a seleção de quais nodes irão rodar os pods é a nível da config do pod, após adicionar essa config
      # neste arquivo, executar este comando: kubectl label nodes minikube-m03 disktype=ssd e só então aplicar o no cluster
        disktype: ssd

  selector: #seleciona o pod para criar replicas através da label do pod
    matchLabels:
     apps: my-app
     #daemonset dispensa especificar a quantidade de replica, pois ele vai replicar o pod em todos os nodes disponíveis
     #automaticamente