apiVersion: batch/v1
kind: Job

metadata:
  name: my-job

spec:
  completions: 10 # Realiza múltiplas execuções, onde cada execução resulta na criação de um novo pod. Por default cria um 1 pod só, parâmetro oopcional
  completionMode: "Indexed" #Cria um índice para o nome dos pods, de modo que seja possível verificar a ordem de criação de cada pod. Parametro opcional
  parallelism: 5 #Indica a quantidade de pods que serão executados em paralelo, por dafault é 1.
  activeDeadlineSeconds: 15 #Define o tempo de execução do job, por default não tem limite por part do k8s. Quando atinge o limite,
  #todos os pods são encerrados, e os que nem começaram a executar tbm não serão encerrados
  template:
    metadata:
      name: my-job-pod
    spec:
      containers:
        - name: my-container-busybox
          image: busybox
          command:
          - "bin/sh"
          - "-c"
          - "for i in 1 2; do echo Lucky number $i = $((1 + RANDOM % 70)); done"
      restartPolicy: Never #não reinicia o container