apiVersion: v1
kind: Pod #tipo do recurso

metadata:
  name: my-pod-webserver
  labels:
    apps: my-app
    tier: frontend

spec: # Especificações referente ao pod que será criado
  containers:
  - name: my-container-nginx
    image: nginx
#  restartPolicy: Never