apiVersion: v1

kind: Secret

metadata:
  name: my-secret

data: #aqui obrigado que estja em base64
  user: YWRtaW4=
  pass: TXktcGFzcy0xMjM=

stringData: #aqui pode ser a string crua
  my-database-name: mysql

#immutable: true