apiVersion: v1
kind: Pod #tipo do recurso

metadata:
  name: specific-node-labels-pod

spec: # Especificações referente ao pod que será criado
  containers:
  - name: my-container-nginx
    image: nginx
  nodeSelector:
    disktype: ssd