apiVersion: v1
kind: Pod

metadata:
  name: pod-secret-vol-env

spec:
  containers:
    - name: my-container
      image: nginx
      envFrom:
      - secretRef:
          name: my-secret # escolhe o secret para aplicar no container
          optional: true
      volumeMounts: #usando volume para o secret, não precisa reiniciar o container pra aplicar a atualização das variaveis de ambiente
      #mas a aplicação precisa ler do conteúdo do volume, se ler do env do container, vai continuar desatualizado
      - name: my-vol
        mountPath: "/etc/my-vol"
        readOnly: true
  volumes:
  - name: my-vol
    secret:
      secretName: my-secret
      optional: true