apiVersion: v1

kind: Secret

metadata:
  name: my-secret

data: #aqui obrigado que estja em base64
  user: YWRtaW4=
  pass: TXktcGFzcy0xMjM=

stringData: #aqui pode ser a string crua
  my-database-name: mysql

#immutable: true
---
apiVersion: v1
kind: Pod

metadata:
  name: pod-secret-vol-env

spec:
  containers:
    - name: my-container
      image: nginx
      envFrom:
      - secretRef:
          name: my-secret # escolhe o secret para aplicar no container
      volumeMounts: #usando volume para o secret, não precisa reiniciar o container pra aplicar a atualização das variaveis de ambiente
      #mas a aplicação precisa ler do conteúdo do volume, se ler do env do container, vai continuar desatualizado
      - name: my-vol
        mountPath: "/etc/my-vol"
        readOnly: true
  volumes:
  - name: my-vol
    secret:
      secretName: my-secret