apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: default

data:
  #Connection database config
  my.config.db: | #dessa forma, usando pipe e deixando as variaveis agrupadas, cria um arquivo apenas, em vez um arquivo por variavel
    database: mariadb
    database_uri: mariadb://localhost:3306
  test.field: hello
  #da forma como feito acima, mesclou as duas formas, agrupando algumas variaveis em um arquivo e gerando um arquivo
  #exclusivo para uma variavel
#immutable: true # não permite que seja atualizado o configMap, será necessário deletar o configMap e cria-lo novamente