apiVersion: v1
kind: Pod

metadata:
  name: pod-configmap-env

spec:
  containers:
    - name: my-container
      image: nginx
      envFrom:
      - configMapRef:
          name: my-configmap # escolhe o configmap para aplicar no container