apiVersion: v1
kind: Pod

metadata:
  name: pod-configmap-vol

spec:
  containers:
    - name: my-container
      image: nginx
      envFrom:
      - configMapRef:
          name: my-configmap # escolhe o configmap para aplicar no container
      volumeMounts: #usando volume para o configmap, não precisa reiniciar o container pra aplicar a atualização das variaveis de ambiente
      #mas a aplicação precisa ler do conteúdo do volume, se ler do env do container, vai continuar desatualizado
      - name: my-vol
        mountPath: "/etc/my-vol"
        readOnly: true
  volumes:
  - name: my-vol
    configMap:
      name: my-configmap